# Generated by Django 4.1.2 on 2022-10-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='creationDatetime',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='releaseDatetime',
            new_name='releaseDate',
        ),
    ]
