# Generated by Django 4.1.2 on 2022-10-16 10:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_isaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='album',
            name='releaseDate',
        ),
        migrations.AddField(
            model_name='album',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='album',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='album',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
