# Generated by Django 4.1.2 on 2022-10-16 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_creationdate_remove_album_releasedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 14, 47, 19, 381067)),
        ),
    ]
