# Generated by Django 4.1.2 on 2022-10-17 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_name_alter_album_release_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 23, 33, 55, 853783)),
        ),
    ]
