# Generated by Django 4.1.2 on 2022-10-17 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_release_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, default='New Album', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 23, 49, 53, 982989)),
        ),
    ]
