# Generated by Django 4.1.2 on 2022-10-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_song_alter_album_release_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 35, 45, 683424)),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(height_field=100, upload_to='images/', width_field=100),
        ),
    ]
