# Generated by Django 4.1.2 on 2022-10-23 11:46

import albums.validatots
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_song_audio_file_alter_album_release_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 46, 20, 453596)),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audio/', validators=[albums.validatots.validate_file_extension]),
        ),
    ]
