# Generated by Django 4.1.2 on 2022-10-23 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_album_release_at_alter_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 13, 57, 3, 455600)),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/', width_field='width'),
        ),
    ]
