# Generated by Django 4.1.2 on 2022-10-23 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_alter_album_release_at_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 15, 38, 44, 747528)),
        ),
    ]
