# Generated by Django 4.1.2 on 2022-10-31 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_release_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='isAccepted',
            new_name='is_accepted',
        ),
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 10, 5, 30, 803599)),
        ),
    ]
