# Generated by Django 4.1.1 on 2022-10-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=250, unique=True)),
                ('social_link', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
