# Generated by Django 4.1.2 on 2022-10-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('stage_name',)},
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='SocialLink',
            new_name='Social_link',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='stageName',
            new_name='stage_name',
        ),
    ]
